mkdir /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/
cd /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/
mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/S288c_R64-1-1.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/S288c_R64-1-1_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/saccharomyces_arboricola.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/saccharomyces_arboricol_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/saccharomyces_eubayanus.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/saccharomyces_eubayanu_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/saccharomyces_jurei.fa /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/saccharomyces_jurei_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/saccharomyces_kudriavzevii.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/saccharomyces_kudriavzevii_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/saccharomyces_mikatae.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/saccharomyces_mikatae_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/saccharomyces_paradoxus.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/saccharomyces_paradoxu_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database/data/genome/yeast_species/pep/saccharomyces_uvarum.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/s288c_yeastsnonref_cov50_pid70_rep_seq.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database/code/4.core_genome_analysis/compare_with_closed_yeasts/output/blastp_vs_s288c_yeastsnonref_cov50_pid70_rep_seq/saccharomyces_uvarum_vs_s288c_yeastsnonref_cov50_pid70_rep_seq_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

