mkdir /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/
cd /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/
mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/S288c_R64.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/343_yeast_genomes/S288c_R64-1-1.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/S288c_R64_vs_S288c_R64-1-1.fasta_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/S288c_R64.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/343_yeast_genomes/saccharomyces_arboricola.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/S288c_R64_vs_saccharomyces_arboricola.fasta_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/S288c_R64.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/343_yeast_genomes/saccharomyces_eubayanus.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/S288c_R64_vs_saccharomyces_eubayanus.fasta_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/S288c_R64.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/343_yeast_genomes/saccharomyces_kudriavzevii.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/S288c_R64_vs_saccharomyces_kudriavzevii.fasta_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/S288c_R64.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/343_yeast_genomes/saccharomyces_mikatae.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/S288c_R64_vs_saccharomyces_mikatae.fasta_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/S288c_R64.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/343_yeast_genomes/saccharomyces_paradoxus.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/S288c_R64_vs_saccharomyces_paradoxus.fasta_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

mmseqs easy-search /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/S288c_R64.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/data/genome/343_yeast_genomes/saccharomyces_uvarum.fasta /mnt/d/code/github/Unified_Yeast_GEMs_Database_from_13pro/Unified_Yeast_GEMs_Database/code/4.pan-genome_analysis/compare_with_closed_yeasts/output/blastp_S288c_R64/S288c_R64_vs_saccharomyces_uvarum.fasta_blastp.txt tmp --min-seq-id 0.6 -e 1e-5

